name: Builds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  #Linux Builds
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Binary
        run: | 
          pyinstaller main.py --onefile --add-data="Ui:Ui"
          pyinstaller admin.py --onefile --add-data="Ui:Ui"
      #Build to AppImage
      - name: Make AppDir (main)
        run: |
          mkdir -p AppDir-main/usr/bin
          cp dist/main AppDir-main/usr/bin/

          echo '#!/bin/bash
          ./usr/bin/main' > AppDir-main/AppRun

          chmod +x AppDir-main/AppRun

      - name: Make AppDir (admin)
        run: |
          mkdir -p AppDir-admin/usr/bin
          cp dist/main AppDir-admin/usr/bin/

          echo '#!/bin/bash
          ./usr/bin/main' > AppDir-admin/AppRun

          chmod +x AppDir-admin/AppRun

      - name: Download AppImageTool And Setup
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2

      - name: Build AppImage (main)
        run: ./appimagetool-x86_64.AppImage AppDir-main InventoryApp.AppImage

      - name: Build AppImage (admin)
        run: ./appimagetool-x86_64.AppImage AppDir-admin InventoryApp[Admin].AppImage
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: "*.AppImage"

  #Windows Build
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE (admin & main)
        run: |
          pyinstaller main.py --onefile --add-data="Ui;Ui"
          pyinstaller admin.py --onefile --add-data="Ui;Ui"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/
